### ISSUE TITLE
As X-Road user I want that Security Server would better comply to SOAP standard.

### ISSUE THREAD

**Issue by VitaliStupin** [vrk-kpa/xroad-joint-development#71]
**Affected components**: proxy
**Affected documentation**: PR-MESS
**Estimated delivery**: -
**External reference**: https://jira.csc.fi/browse/PVAYLADEV-800 (https://jira.ria.ee/browse/XTE-268)

**Problem**
https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528
"The SOAPAction HTTP request header field can be used to indicate the intent of the SOAP HTTP request. ... An HTTP client MUST use this header field when issuing a SOAP HTTP Request"
Security server must preserve SOAPAction header.

**Acceptance criteria**
- Protocol description is updated
- Security server preserves SOAPAction header.
- Security server still accepts requests without SOAPAction header.

**Comment by petkivim** [comment]
In addition, Security Server must accept requests without SOAPAction header too. If client uses SOAPAction header, Security Server must preserve it. If client does not use SOAPAction header, Security Server accepts the request and does not add SOAPAction header automatically.

This is very important for backwards compatibility. Rejecting requests without SOAPAction header could break current adapter server implementations.

**Comment by hanhaka** [comment]
Agreed to be fixed to next X-Road version.

**Comment by vahem2lu** [comment]
Just in case - yesterday was released 6.16.0-0.20170808. Is it fixed there or not yet?

**Comment by hanhaka** [comment]
The fix is not yet in this version (=mentioned above), we are still working on it. However implementation 
 work and the tests are already done but the code changes are not yet merged to Github repository. Current schedule is to release version in the beginning of September that includes this fix.

**Comment by hanhaka** [comment]
Fixed in 6.16.0, https://github.com/ria-ee/X-Road/pull/61

**Comment by vahem2lu** [comment]
Hi.
Thank you for this fix!

SOAP standard requires that this "soapAction" header needs to be there. Even if it is empty.
Can you please **disallow** missing soapAction and
a) reject the query totally with proper error code, if possible
b) if soapAction header is missing, add empty soapAction header.

Right now without a soapAction in header result is basically the same:

> System.Web.Services.Protocols.SoapException: Unable to handle request without a valid action parameter. Please supply a valid soap action.

Thank you!

**Comment by hanhaka** [comment]
Hi,

thanks for your comments. 

Unfortunately we cannot force the Security Server to add the "soapAction" header if it is missing from the original SOAP message or give an error message as indication of it. That would break the backwards compatibility of X-Road because previously it was not the mandatory header even the SOAP standard requires it. Sadly the previous versions of X-Road had incomplete implementation and we have to deal with that technical depth now.

Thanks.

**Comment by vahem2lu** [comment]
Hi

It seems that this is still not working, as SOAPAction header gets lost in securityserver.
Using xroad-securityserver version 6.16.0-0.20170808152243git6e94fd4.

**Comment by VitaliStupin** [comment]
You are using snapshot version of 6.16.0 created at 2017-06-20 while this feature was implemented at 2017-08-17.

**Comment by vahem2lu** [comment]
How and when I can use this fixed version? As X-road repositories (both test and live) are showing this snapshot version.
